# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevelopeLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit'
  # Pods for DevelopeLibrary

  target 'DevelopeLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DevelopeLibraryUITests' do
    # Pods for testing
  end

end
